### ISSUE TITLE
ValueError for different input

### ISSUE THREAD

**Issue by malavikaanand15** [vismaya74/git_demo#2]
enter first number 0x10 
Traceback (most recent call last):
  File "/home/malavika/Documents/git_demo/calculator.py", line 2, in <module>
    a=int(input('enter first number '))
ValueError: invalid literal for int() with base 10: '0x10'

**Comment by vismaya74** [comment]
u can now check.

**Comment by malavikaanand15** [comment]
![Screenshot from 2023-01-11 10-56-35](https://user-images.githubusercontent.com/120602449/211724788-18feac22-6b34-41b3-b15f-3d04863192f6.png)

Not accepting string datatype

**Comment by vismaya74** [comment]
hi malavika,
I have updated the code. Please check
